// Generated by CoffeeScript 2.3.1
(function() {
  var delta, i, j, n, pi, ref, sum, x;

  n = 1000000000;

  delta = 1.0 / n;

  sum = 0.0;

  x;

  for (i = j = 1, ref = n; (1 <= ref ? j < ref : j > ref); i = 1 <= ref ? ++j : --j) {
    x = (i - 0.5) * delta;
    sum = sum + (1.0 / (1.0 + x * x));
  }

  pi = 4.0 * delta * sum;

  console.log(pi);

  console.log((n.toString()).length);

}).call(this);
